use_frameworks!

target 'KVOMutableArray_Example' do
  pod 'KVOMutableArray/ReactiveCocoaSupport', :path => '../'

  target 'KVOMutableArray_Tests' do
    inherit! :search_paths
    pod 'KVOMutableArray/ReactiveCocoaSupport', :path => '../'
  end
end
